<?php
// $Id$

/**
 * @file
 * Install, update and uninstall functions for the database_test module.
 */

/**
 * Implements hook_schema().
 */
function database_test_schema() {
  $schema['test'] = array(
    'description' => 'Basic test table for the database unit tests.',
    'fields' => array(
      'id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'name' => array(
        'description' => "A person's name",
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'age' => array(
        'description' => "The person's age",
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
      ),
      'job' => array(
        'description' => "The person's job",
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => 'Undefined',
      ),
    ),
    'primary key' => array('id'),
    'unique keys' => array(
      'name' => array('name')
    ),
    'indexes' => array(
      'ages' => array('age'),
    ),
  );

  return $schema;
}

/**
 * Implemetation of hook_install().
 */
function database_test_install() {
  drupal_install_schema('database_test');
}

/**
 * Implemetation of hook_enable().
 */
function database_test_enable() {
  cache_clear_all();
}

/**
 * Implemetation of hook_uninstall().
 */
function database_test_uninstall() {
  drupal_uninstall_schema('database_test');
}
